version: "3.7"

services:
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=database
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    tmpfs: /var/lib/postgresql/data

  wmmc_bot:
    image: wmmc_bot:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/New_York
      BOT_TOKEN: "top.secret"
      ALERT_CHAN_ID: 719692563405078620
      WEATHER_CHAN_ID: 719692563405078620
    restart: "no"
    command: "true"
